version: '3.8'

services:
  postgres-copilot:
    build:
      context: .
    user: "${CURRENT_UID:-0}:${CURRENT_GID:-0}"
    volumes:
      - ./data:/home/appuser/data
    environment:
      - POSTGRES_COPILOT_DATA_DIR=/home/appuser/data
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
